### PR TITLE
Some quality of life changes, some hopeful fixes and additional cleanup

### LINKED ISSUE #7: Warn if LICENCE not provided
Right now LICENCE defaults to "notset" which just causes the activation to fail. Might be nice to provide a more user friendly warning ahead of time by checking if the variable is actually set.

### LINKED ISSUE #19: Incorrect CPU Usage?
It seems that the CPU usage reported by AMP is much lower than the real CPU usage at all times. This might be a docker thing or it might be just my server. Can anyone confirm?

### PR DESCRIPTION
**Pull request by Joly0**
Changed a few things regarding the location of the downloaded ampinstmgr files, /opt is there for exactly that and it would be a good idea to use that path, amp uses it for itself usually.

Additionally, some cleanup, things like the second debian_frontend=noninteractive arg is not needed, aswell as the repo for cubecoders, as we dont download through apt anyway.

Lastly some changes, that should fix #7 and might fix #19 although i am not sure with that, its a tricky one as there is no documentation and discord doesnt help... we will see

Oh, and it might be worth to consider updating to 20.04 or maybe to debian buster or so

### CODE REVIEW

**Comment by MitchTalmadge** [comment]
Thanks for the contribution! 

The reason I use `/home/.ampdata/bin` for ampinstmgr is that it needs to persist between container restarts, and this location is already a volume. If we place it in `/opt`, then if the container gets removed (such as when updating from one version of this image to the next), the next time it comes up `ampinstmgr` will be missing and this image will break because it expects that it exists. Or it would have to be re-downloaded, which is not necessary if we store it in the volume. I'd rather not ask the user to make two volumes.

I will test the rest of the changes (they look nice!), and yeah if you'd like to bump it up to 20.04 I'd love to see if we can get that working!

**Comment by Joly0** [comment]
Yeah, i get that with the storage location of ampinstmgr, there are some reasons why i dislike the idea of exposing it to the user. In general it comes with some problems that could come up like files getting deleted or permissions getting changed wrong by the user, resulting in an issue, where the user would come back to us. Furthermore docker containers usually are built to be as is, so normally when a new version of ampinstmgr comes out, we should built a new container, rather then this approach, thats just the way docker should be used. My suggestion here would be, to maybe hide the bin folder in some way, we should look into that.

Other than that, i am happy to help.

**Comment by Joly0** [comment]
Had no time to look into this in the previous time but now i changed the path back to how it was but placed it in a hidden folder, so its safer to use like this

**Comment by Joly0** [comment]
Will look into updating it either to 20.04 or to debian buster soon, but going to create another pull request for that

File: entrypoint/update-ampinstmgr.sh [hunk 1]
```diff
@@ -22,10 +22,9 @@ else
 fi
 
 echo "Downloading latest ampinstmgr... (This can take ~5 minutes; CubeCoders limits their download speeds to a crawl.)"
-DL_PATH=/tmp/ampinstmgr.zip
-wget -nv http://cubecoders.com/Downloads/ampinstmgr.zip -O ${DL_PATH}
+wget -nv -P ${AMP_BIN_DIR} http://cubecoders.com/Downloads/ampinstmgr.zip
```
Comment (MitchTalmadge) [inline entrypoint/update-ampinstmgr.sh:25]: Why do you remove the `DL_PATH`? The reason I download to a `tmp` path is in case the container is shut down in the middle of download. Writing it to the volume will cause an unfinished download to linger. Perhaps we should add the `-c` (continue) argument to `wget` which should continue the interrupted download. What do you think?

File: entrypoint/main.sh [hunk 2]
```diff
@@ -23,6 +23,9 @@ fi
 APP_USER=$(getent passwd ${UID} | awk -F ":" '{ print $1 }')
 chown -R ${APP_USER}:${APP_GROUP} /home/amp
 
+# Ensure a Licence was set
```
Comment (MitchTalmadge) [inline entrypoint/main.sh:26]: Thanks for doing this!

File: Dockerfile [hunk 3]
```diff
@@ -71,11 +73,6 @@ RUN wget -O /tmp/cacert.pem https://curl.haxx.se/ca/cacert.pem && \
     cert-sync /tmp/cacert.pem
 
 
-# Add CubeCoders apt source
```
Comment (MitchTalmadge) [inline Dockerfile:74]: Good catch

File: Dockerfile [hunk 4]
```diff
@@ -34,7 +34,8 @@ RUN apt-get update && \
     /var/lib/apt/lists/* \
     /var/tmp/*
 RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
-  locale-gen
+    dpkg-reconfigure --frontend=noninteractive locales && \
```
Comment (MitchTalmadge) [inline Dockerfile:37]: What's the change here do? Just curious

**Review by MitchTalmadge — CHANGES_REQUESTED** [review]
This is looking really good! Thanks for all the help. Just a few questions/suggestions

**Comment by MitchTalmadge** [comment]
> Yeah, i get that with the storage location of ampinstmgr, there are some reasons why i dislike the idea of exposing it to the user. In general it comes with some problems that could come up, like files getting deleted or permissions getting changed wrong by the user, resulting in an issue, where the user would come back here. Furthermore docker containers usually are built to be as is, so normally when a new version of ampinstmgr comes out, we should built a new container, rather then this approach, thats just the way docker should be used. My suggestion here would be, to maybe hide the bin folder in some way, we should look into that.
> 
> Other than that, i am happy to help.

Yeah I see what you mean. That's probably a better way to do things than I am doing. I worry about making this change since a lot of people already use the container, and I think most people rely on just restarting the container to update ampinstmgr instead of pulling a new image. ...but I guess old images would still work, so it would only affect new versions. I am going to play with this idea when I get some free time.

File: entrypoint/main.sh [hunk 5]
```diff
@@ -60,7 +63,7 @@ su ${APP_USER} --command "ampinstmgr ShowInstanceInfo Main | grep \"Start on Boo
 
 # Startup
 echo "Starting AMP..."
-su ${APP_USER} --command "ampinstmgr StartBoot"
+su ${APP_USER} --command "ampinstmgr StartBoot" &
```
[the remark this answers is not in the document]
Comment (Joly0) [reply entrypoint/main.sh:66]: It might be a nieche-case, but i experienced problems in the past when amp was in foreground and was not able to start correcrly ehich resulted in the whole container to crash. The best workaround i found was starting it in background. But that was some time ago and it might have changed in the mean time, so i think we could leave it in the forefround.

File: entrypoint/update-ampinstmgr.sh (hunk 1 above)
Comment (Joly0) [reply entrypoint/update-ampinstmgr.sh:25]: Yeah, your right with this one, but what i initially wanted to achieve is not downloading amp every time the container starts. Usually ampinstmgr shares the same version-numbering scheme with ampcore, so downloading both when one gets an update moght be better then downloading one when it updates an the second when the container restarts. So to make it persistent, i shifted it over to the volume. That might also help with testing, as you dont have to download it every time first.

I have to look a bit more into this first, but this was my initial intention.

File: Dockerfile (hunk 4 above)
Comment (Joly0) [reply Dockerfile:37]: It basically does the same as locale-gen, but its more general. Locale-gen sometimes does not work correctly in some distributions, like debian, or might not behave as intended in newer versions of ubuntu, so i just replaced it with a generalized command. We could still use locale-gen, it might even be better, just wanted to be prepared for the future, when it might not work correctly anymore.

Comment (MitchTalmadge) [reply Dockerfile:37]: If it builds and works then I'm cool with the change :)

File: entrypoint/main.sh (hunk 5 above)
[the remark this answers is not in the document]
Comment (MitchTalmadge) [reply entrypoint/main.sh:66]: Ok, let's leave it as foreground and let me know if the issue pops up again!

File: entrypoint/update-ampinstmgr.sh (hunk 1 above)
Comment (MitchTalmadge) [reply entrypoint/update-ampinstmgr.sh:25]: Ah I see, there's definitely room for optimization. How about we just add the `-c` flag, which will allow the download to continue if it fails, then we can leave it downloading where it is. Like I mentioned [here](https://github.com/MitchTalmadge/AMP-dockerized/pull/36#issuecomment-732456427) I would love to look into a different way of downloading ampinstmgr in the future, so we can come back to this!

**Comment by Joly0** [comment]
> > Yeah, i get that with the storage location of ampinstmgr, there are some reasons why i dislike the idea of exposing it to the user. In general it comes with some problems that could come up, like files getting deleted or permissions getting changed wrong by the user, resulting in an issue, where the user would come back here. Furthermore docker containers usually are built to be as is, so normally when a new version of ampinstmgr comes out, we should built a new container, rather then this approach, thats just the way docker should be used. My suggestion here would be, to maybe hide the bin folder in some way, we should look into that.
> > Other than that, i am happy to help.
> 
> Yeah I see what you mean. That's probably a better way to do things than I am doing. I worry about making this change since a lot of people already use the container, and I think most people rely on just restarting the container to update ampinstmgr instead of pulling a new image. ...but I guess old images would still work, so it would only affect new versions. I am going to play with this idea when I get some free time; I do like it a lot. It would cut down on download times I think.

Just want to add on this one: Adding this in a proper way would mean shifting some work from the bash files to the dockefile which would result in a bigger intial-download size for the user, but easier updates for us, aswell as better control over the whole system. But we might need a proper ci/cd for that. But i will look into this aswell, as it would mean some bigger changes, so "installing" to a hidden folder is for the moment a better starting point then exposing it directly

**Comment by MitchTalmadge** [comment]
> Just want to add on this one: Adding this in a proper way would mean shifting some work from the bash files to the dockefile which would result in a bigger intial-download size for the user, but easier updates for us, aswell as better control over the whole system. But we might need a proper ci/cd for that. But i will look into this aswell, as it would mean some bigger changes, so "installing" to a hidden folder is for the moment a better starting point then exposing it directly

Yeah we would need CI/CD for sure. I was thinking we could use GitHub Actions for this. The actions can run on a cron schedule, detect an updated ampinstmgr, and then build a new container with the latest ampinstmgr. I'm not sure how the tagging scheme would go. I am imagining two ways of doing it. We could either make a unique tag for every ampinstmgr update along with this container's version, or we could just replace this container's version with the latest ampinstmgr. 

Example of having a unique tag for each ampinstmgr:
- mitchtalmadge/amp-dockerized:release-5_amp-2-0-8-6

Example of just replacing our versions each time:
- mitchtalmadge/amp-dockerized:release-5

Or other ideas are welcome.

**Comment by Joly0** [comment]
Ok, i am gomna work on this a bit more in the next days and see, where i can improve this more and change a few things you mentioned. Maybe i could be able to get this updated to 20.04, already works on my local fork, but might need someome to test srcds compatibilty, as some packages are not updated yet or not getting updated.

**Comment by Joly0** [comment]
> > Just want to add on this one: Adding this in a proper way would mean shifting some work from the bash files to the dockefile which would result in a bigger intial-download size for the user, but easier updates for us, aswell as better control over the whole system. But we might need a proper ci/cd for that. But i will look into this aswell, as it would mean some bigger changes, so "installing" to a hidden folder is for the moment a better starting point then exposing it directly
> 
> The bigger initial download is okay, they will end up downloading that much data anyway as-is, just later (and slower).
> 
> Yeah we would need CI/CD for sure. I was thinking we could use GitHub Actions for this. The actions can run on a cron schedule, detect an updated ampinstmgr, and then build a new container with the latest ampinstmgr. I'm not sure how the tagging scheme would go. I am imagining two ways of doing it. We could either make a unique tag for every ampinstmgr update along with this container's version, or we could just replace this container's version with the latest ampinstmgr.
> 
> Example of having a unique tag for each ampinstmgr:
> 
>     * mitchtalmadge/amp-dockerized:release-5_amp-2-0-8-6
> 
> 
> Example of just replacing our versions each time:
> 
>     * mitchtalmadge/amp-dockerized:release-5
> 
> 
> Or other ideas are welcome.

Will look into this, but i would highly suggest not replacing, but using unique tags, as that would make testing easier for different versions and cross-comparision, and would make it easier to identify which explicit version one is running.

**Review by Joly0 — COMMENTED** [review]
wget now continues the download if it stops, but hopefully we find a better solution for this soon. Amp now starts in foreground

**Comment by Joly0** [comment]
Btw we should definitly find a better solution for installing everything. It takes way too long to do apt update so often

**Comment by MitchTalmadge** [comment]
Thanks! Looks good! I'll find time to test and release sometime this week.

**Review by MitchTalmadge — APPROVED** [review]

**Comment by MitchTalmadge** [comment]
> Btw we should definitly find a better solution for installing everything. It takes way too long to do apt update so often

What do you suggest?

**Comment by Joly0** [comment]
> 
> 
> > Btw we should definitly find a better solution for installing everything. It takes way too long to do apt update so often
> 
> What do you suggest?

Well, the only real solution to this is a apt install one-liner instead of splitting it up into multiple layers. That could shrink the image size a bit aswell, but we already talked about that, its not the best solution. But when we implement a ci/cd we could definitly look into multi-stage builds, which should reduce size aswell, but wouldnt help with build time
